/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as UsernameSlugRouteImport } from './routes/$username/$slug'
import { Route as AuthedBuilderRouteRouteImport } from './routes/_authed/builder/route'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as PublicSignInIndexRouteImport } from './routes/_public/sign-in/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TestTemplateIndexRouteImport } from './routes/test/template/index'
import { Route as AuthedBuilderResumesResume_idRouteImport } from './routes/_authed/builder/resumes/$resume_id'
import { Route as AuthedDashboardProfileIndexRouteImport } from './routes/_authed/dashboard/profile/index'
import { Route as AuthedDashboardResumesIndexRouteImport } from './routes/_authed/dashboard/resumes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameSlugRoute = UsernameSlugRouteImport.update({
  id: '/$username/$slug',
  path: '/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBuilderRouteRoute = AuthedBuilderRouteRouteImport.update({
  id: '/_authed/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/_authed/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const PublicSignInIndexRoute = PublicSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTemplateIndexRoute = TestTemplateIndexRouteImport.update({
  id: '/test/template/',
  path: '/test/template/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBuilderResumesResume_idRoute =
  AuthedBuilderResumesResume_idRouteImport.update({
    id: '/resumes/$resume_id',
    path: '/resumes/$resume_id',
    getParentRoute: () => AuthedBuilderRouteRoute,
  } as any)
const AuthedDashboardProfileIndexRoute =
  AuthedDashboardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardResumesIndexRoute =
  AuthedDashboardResumesIndexRouteImport.update({
    id: '/resumes/',
    path: '/resumes/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof AuthedBuilderRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/$username/$slug': typeof UsernameSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/sign-in/': typeof PublicSignInIndexRoute
  '/test/template/': typeof TestTemplateIndexRoute
  '/builder/resumes/$resume_id': typeof AuthedBuilderResumesResume_idRoute
  '/dashboard/profile/': typeof AuthedDashboardProfileIndexRoute
  '/dashboard/resumes/': typeof AuthedDashboardResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof AuthedBuilderRouteRouteWithChildren
  '/$username/$slug': typeof UsernameSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/sign-in': typeof PublicSignInIndexRoute
  '/test/template': typeof TestTemplateIndexRoute
  '/builder/resumes/$resume_id': typeof AuthedBuilderResumesResume_idRoute
  '/dashboard/profile': typeof AuthedDashboardProfileIndexRoute
  '/dashboard/resumes': typeof AuthedDashboardResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authed/builder': typeof AuthedBuilderRouteRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/$username/$slug': typeof UsernameSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_public/sign-in/': typeof PublicSignInIndexRoute
  '/test/template/': typeof TestTemplateIndexRoute
  '/_authed/builder/resumes/$resume_id': typeof AuthedBuilderResumesResume_idRoute
  '/_authed/dashboard/profile/': typeof AuthedDashboardProfileIndexRoute
  '/_authed/dashboard/resumes/': typeof AuthedDashboardResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/dashboard'
    | '/$username/$slug'
    | '/api/auth/$'
    | '/dashboard/'
    | '/sign-in/'
    | '/test/template/'
    | '/builder/resumes/$resume_id'
    | '/dashboard/profile/'
    | '/dashboard/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/$username/$slug'
    | '/api/auth/$'
    | '/dashboard'
    | '/sign-in'
    | '/test/template'
    | '/builder/resumes/$resume_id'
    | '/dashboard/profile'
    | '/dashboard/resumes'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/_authed/builder'
    | '/_authed/dashboard'
    | '/$username/$slug'
    | '/api/auth/$'
    | '/_authed/dashboard/'
    | '/_public/sign-in/'
    | '/test/template/'
    | '/_authed/builder/resumes/$resume_id'
    | '/_authed/dashboard/profile/'
    | '/_authed/dashboard/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthedBuilderRouteRoute: typeof AuthedBuilderRouteRouteWithChildren
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
  UsernameSlugRoute: typeof UsernameSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TestTemplateIndexRoute: typeof TestTemplateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$slug': {
      id: '/$username/$slug'
      path: '/$username/$slug'
      fullPath: '/$username/$slug'
      preLoaderRoute: typeof UsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/builder': {
      id: '/_authed/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthedBuilderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_public/sign-in/': {
      id: '/_public/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof PublicSignInIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/template/': {
      id: '/test/template/'
      path: '/test/template'
      fullPath: '/test/template/'
      preLoaderRoute: typeof TestTemplateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/builder/resumes/$resume_id': {
      id: '/_authed/builder/resumes/$resume_id'
      path: '/resumes/$resume_id'
      fullPath: '/builder/resumes/$resume_id'
      preLoaderRoute: typeof AuthedBuilderResumesResume_idRouteImport
      parentRoute: typeof AuthedBuilderRouteRoute
    }
    '/_authed/dashboard/profile/': {
      id: '/_authed/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof AuthedDashboardProfileIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/resumes/': {
      id: '/_authed/dashboard/resumes/'
      path: '/resumes'
      fullPath: '/dashboard/resumes/'
      preLoaderRoute: typeof AuthedDashboardResumesIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicSignInIndexRoute: typeof PublicSignInIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSignInIndexRoute: PublicSignInIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AuthedBuilderRouteRouteChildren {
  AuthedBuilderResumesResume_idRoute: typeof AuthedBuilderResumesResume_idRoute
}

const AuthedBuilderRouteRouteChildren: AuthedBuilderRouteRouteChildren = {
  AuthedBuilderResumesResume_idRoute: AuthedBuilderResumesResume_idRoute,
}

const AuthedBuilderRouteRouteWithChildren =
  AuthedBuilderRouteRoute._addFileChildren(AuthedBuilderRouteRouteChildren)

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardProfileIndexRoute: typeof AuthedDashboardProfileIndexRoute
  AuthedDashboardResumesIndexRoute: typeof AuthedDashboardResumesIndexRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardProfileIndexRoute: AuthedDashboardProfileIndexRoute,
  AuthedDashboardResumesIndexRoute: AuthedDashboardResumesIndexRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthedBuilderRouteRoute: AuthedBuilderRouteRouteWithChildren,
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
  UsernameSlugRoute: UsernameSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TestTemplateIndexRoute: TestTemplateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
